// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minemation.Infrastructure.Persistence;

#nullable disable

namespace Minemation.Infrastructure.Migrations
{
    [DbContext(typeof(MinemationDbContext))]
    [Migration("20260509130814_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kirici", b =>
                {
                    b.Property<int>("ekipmanId")
                        .HasColumnType("int");

                    b.Property<decimal>("calismaBasinci")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("dakikadakiDarbeSayisi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("darbeEnerjisi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("gerekenYagDebisi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ucTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ekipmanId");

                    b.ToTable("Kirici");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.AcilDurumIletisim", b =>
                {
                    b.Property<int>("acilDurumKisisiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("acilDurumKisisiId"));

                    b.Property<string>("acilDurumKisileriAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("acilDurumKisileriSoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("acilDurumKisileriTelNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("acilDurumKisileriYakinlik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("personelId")
                        .HasColumnType("int");

                    b.HasKey("acilDurumKisisiId");

                    b.HasIndex("personelId");

                    b.ToTable("AcilDurumIletisim");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Aksiyon", b =>
                {
                    b.Property<int>("mudahaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mudahaleId"));

                    b.Property<int>("ekipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("mudahaleBaslangicSaati")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("mudahaleBitisSaati")
                        .HasColumnType("datetime2");

                    b.Property<string>("mudahaleTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("uygulananCozum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("vakaId")
                        .HasColumnType("int");

                    b.HasKey("mudahaleId");

                    b.HasIndex("ekipId");

                    b.HasIndex("vakaId");

                    b.ToTable("Aksiyon");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Ekip", b =>
                {
                    b.Property<int>("ekipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ekipId"));

                    b.Property<string>("durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ekipUyeSayisi")
                        .HasColumnType("int");

                    b.Property<string>("personelGorevi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("personelId")
                        .HasColumnType("int");

                    b.Property<int>("vardiyaId")
                        .HasColumnType("int");

                    b.HasKey("ekipId");

                    b.HasIndex("personelId");

                    b.HasIndex("vardiyaId");

                    b.ToTable("Ekip");

                    b.HasData(
                        new
                        {
                            ekipId = 1,
                            durum = "Görevde",
                            ekipUyeSayisi = 1,
                            personelGorevi = "Vardiya Amiri",
                            personelId = 1,
                            vardiyaId = 1
                        });
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Ekipman", b =>
                {
                    b.Property<int>("ekipmanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ekipmanId"));

                    b.Property<string>("RFIDEtiket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("agirlik")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("bakimFormu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("boyut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ekipmanAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ekipmanMarka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ekipmanModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("garantiBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("garantiBelgesi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("gelecekBakimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("kullanimKilavuzu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("operasyonTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("satinAlmaBelgesi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("satinAlmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("seriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("sonBakimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("tedarikciFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teknikDokuman")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ureticiFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("uretimYili")
                        .HasColumnType("datetime2");

                    b.HasKey("ekipmanId");

                    b.ToTable("Ekipman");

                    b.HasData(
                        new
                        {
                            ekipmanId = 101,
                            RFIDEtiket = "TAG-EQ-101",
                            agirlik = 94000.00m,
                            bakimFormu = "/docs/service.pdf",
                            boyut = 12.50m,
                            durum = "Aktif",
                            ekipmanAdi = "Dev Ekskavatör CAT-395",
                            ekipmanMarka = "Caterpillar",
                            ekipmanModel = "395-L",
                            garantiBaslangicTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            garantiBelgesi = "/docs/warranty.pdf",
                            gelecekBakimTarihi = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            kullanimKilavuzu = "/docs/manual.pdf",
                            operasyonTuru = "Kazı ve Yükleme",
                            satinAlmaBelgesi = "/docs/invoice.pdf",
                            satinAlmaTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            seriNo = "SN-CAT-999",
                            sonBakimTarihi = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            tedarikciFirma = "Borusan Makina",
                            teknikDokuman = "/docs/cat395.pdf",
                            ureticiFirma = "CAT Global",
                            uretimYili = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Minemation.Domain.Entities.EkipmanRaporu", b =>
                {
                    b.Property<int>("raporId")
                        .HasColumnType("int");

                    b.Property<int>("arizaSayisi")
                        .HasColumnType("int");

                    b.Property<int>("calismaSuresi")
                        .HasColumnType("int");

                    b.Property<string>("ekipmanTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("raporId");

                    b.ToTable("EkipmanRaporu");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Ekskavator", b =>
                {
                    b.Property<int>("ekipmanId")
                        .HasColumnType("int");

                    b.Property<decimal>("bomUzunlugu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("kovaKapasitesi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("maksimumKaziDerinligi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("motorGucu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("paletTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("plaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ekipmanId");

                    b.ToTable("Ekskavator");

                    b.HasData(
                        new
                        {
                            ekipmanId = 101,
                            bomUzunlugu = 7.2m,
                            kovaKapasitesi = 6.5m,
                            maksimumKaziDerinligi = 9.7m,
                            motorGucu = 543m,
                            paletTipi = "Çelik Ağır Hizmet",
                            plaka = "06 MINE 01"
                        });
                });

            modelBuilder.Entity("Minemation.Domain.Entities.ElAletleri", b =>
                {
                    b.Property<int>("ekipmanId")
                        .HasColumnType("int");

                    b.Property<decimal>("bataryaKapasitesi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("gucKaynagiTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("kullanimAmaci")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ekipmanId");

                    b.ToTable("ElAletleri");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Hafriyat", b =>
                {
                    b.Property<int>("ekipmanId")
                        .HasColumnType("int");

                    b.Property<decimal>("azamiYukAgirligi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("damperHacmi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("dingilSayisi")
                        .HasColumnType("int");

                    b.Property<string>("plaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ekipmanId");

                    b.ToTable("Hafriyat");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Kepce", b =>
                {
                    b.Property<int>("ekipmanId")
                        .HasColumnType("int");

                    b.Property<decimal>("bosaltmaYuksekligi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("devrilmeYuku")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("kovaKapasitesi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("plaka")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("yuklemeKapasitesi")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ekipmanId");

                    b.ToTable("Kepce");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.LogKaydi", b =>
                {
                    b.Property<int>("logKaydiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logKaydiID"));

                    b.Property<string>("durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ekipmanId")
                        .HasColumnType("int");

                    b.Property<string>("ipAdresi")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("islemTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("logKaydiAciklamasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("logKaydiTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("onemSeviyesi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("personelId")
                        .HasColumnType("int");

                    b.HasKey("logKaydiID");

                    b.HasIndex("ekipmanId");

                    b.HasIndex("personelId");

                    b.ToTable("LogKaydi");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Personel", b =>
                {
                    b.Property<int>("personelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("personelId"));

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("calisanTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("calismaKonumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ikinciTelNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("iseGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("kullaniciRolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personelAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personelDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("personelSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rfidKartNumarasi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("sonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("tckn")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<string>("telNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uzmanlik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personelId");

                    b.ToTable("Personeller");

                    b.HasData(
                        new
                        {
                            personelId = 1,
                            adres = "Ankara",
                            calisanTipi = "Tam Zamanlı",
                            calismaKonumu = "Merkez Sahası",
                            cinsiyet = "Kadın",
                            departman = "Yönetim",
                            dogumTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            eposta = "busra@minemation.com",
                            ikinciTelNo = "05551112234",
                            iseGirisTarihi = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            kullaniciRolu = "Admin",
                            personelAdi = "Büşra",
                            personelDurumu = "Aktif",
                            personelSoyadi = "Arslan",
                            rfidKartNumarasi = "RFID-001",
                            sifreHash = "AQAAAAEAACcQAAAAE...",
                            sonGirisTarihi = new DateTime(2026, 5, 9, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            tckn = "12345678901",
                            telNo = "05551112233",
                            uzmanlik = "Mühendis"
                        });
                });

            modelBuilder.Entity("Minemation.Domain.Entities.PersonelRaporu", b =>
                {
                    b.Property<int>("raporId")
                        .HasColumnType("int");

                    b.Property<decimal>("calismaSuresi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("personelSayisi")
                        .HasColumnType("int");

                    b.Property<string>("uzmanlikAlani")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("raporId");

                    b.ToTable("PersonelRaporu");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Rapor", b =>
                {
                    b.Property<int>("raporId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("raporId"));

                    b.Property<int?>("ekipmanId")
                        .HasColumnType("int");

                    b.Property<int?>("personelId")
                        .HasColumnType("int");

                    b.Property<string>("raporAciklamasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("raporAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("raporDosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("raporOlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("raporTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zamanAraligi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("raporId");

                    b.HasIndex("ekipmanId");

                    b.HasIndex("personelId");

                    b.ToTable("Rapor");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.SaglikBilgileri", b =>
                {
                    b.Property<int>("personelId")
                        .HasColumnType("int");

                    b.Property<string>("acilDurumNotu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("alerjiler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kanGrubu")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("kronikHastaliklar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saglikCalismaKisitlamalari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saglikDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("sonMuayeneTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("personelId");

                    b.ToTable("SaglikBilgileri");

                    b.HasData(
                        new
                        {
                            personelId = 1,
                            acilDurumNotu = "İlaç alerjisi yok.",
                            alerjiler = "[\"Polen\"]",
                            kanGrubu = "A Rh+",
                            kronikHastaliklar = "[]",
                            saglikCalismaKisitlamalari = "Yok",
                            saglikDurumu = "Genel sağlık durumu iyi.",
                            sonMuayeneTarihi = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Sensor", b =>
                {
                    b.Property<int>("ekipmanId")
                        .HasColumnType("int");

                    b.Property<string>("baglantiProtokolu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("haberlesmeTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("hassasiyet")
                        .HasColumnType("float");

                    b.Property<double>("maxEsikDeger")
                        .HasColumnType("float");

                    b.Property<double>("minEsikDeger")
                        .HasColumnType("float");

                    b.Property<string>("sensorDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("sensorTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ekipmanId");

                    b.ToTable("Sensor");

                    b.HasData(
                        new
                        {
                            ekipmanId = 101,
                            baglantiProtokolu = "MQTT",
                            haberlesmeTipi = "Kablosuz 4G",
                            hassasiyet = 0.5,
                            maxEsikDeger = 110.0,
                            minEsikDeger = 20.0,
                            sensorDurumu = "Aktif",
                            sensorTipi = "Sıcaklık ve Basınç"
                        });
                });

            modelBuilder.Entity("Minemation.Domain.Entities.SensorVerisi", b =>
                {
                    b.Property<int>("sensorVerisiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sensorVerisiId"));

                    b.Property<string>("birim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("deger")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ekipmanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("olcumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("vardiyaId")
                        .HasColumnType("int");

                    b.HasKey("sensorVerisiId");

                    b.HasIndex("ekipmanId");

                    b.HasIndex("vardiyaId");

                    b.ToTable("SensorVerisi");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.TakipCihazi", b =>
                {
                    b.Property<int>("takipCihaziId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("takipCihaziId"));

                    b.Property<int?>("ekipmanId")
                        .HasColumnType("int");

                    b.Property<int?>("personelId")
                        .HasColumnType("int");

                    b.Property<decimal>("pilSeviyesi")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("takipCihaziDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("takipCihaziHaberlesmeProtokolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("takipCihaziModeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("takipCihaziSeriNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("takipCihaziSonBaglantiZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("takipCihaziTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("takipCihaziId");

                    b.HasIndex("ekipmanId");

                    b.HasIndex("personelId");

                    b.ToTable("TakipCihazi");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Vaka", b =>
                {
                    b.Property<int>("vakaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vakaId"));

                    b.Property<int?>("ilgiliEkipmanId")
                        .HasColumnType("int");

                    b.Property<string>("olayNedeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("personelId")
                        .HasColumnType("int");

                    b.Property<int?>("raporlayanEkipmanId")
                        .HasColumnType("int");

                    b.Property<string>("vakaAciklamasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("vakaAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("vakaCiddiyetSeviyesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vakaDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("vakaKapanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("vakaOlusmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("vakaTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vakaId");

                    b.HasIndex("ilgiliEkipmanId");

                    b.HasIndex("personelId");

                    b.HasIndex("raporlayanEkipmanId");

                    b.ToTable("Vaka");

                    b.HasData(
                        new
                        {
                            vakaId = 1,
                            ilgiliEkipmanId = 101,
                            olayNedeni = "Soğutma sıvısı sızıntısı şüphesi",
                            personelId = 1,
                            vakaAciklamasi = "Sensör verisi normalin üzerine çıktı.",
                            vakaAdi = "Yüksek Motor Sıcaklığı",
                            vakaCiddiyetSeviyesi = "Kritik",
                            vakaDurumu = "İncelemede",
                            vakaOlusmaTarihi = new DateTime(2026, 5, 9, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            vakaTuru = "Teknik Arıza"
                        });
                });

            modelBuilder.Entity("Minemation.Domain.Entities.VakaRaporu", b =>
                {
                    b.Property<int>("raporId")
                        .HasColumnType("int");

                    b.Property<string>("ciddiyetSeviyesi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("cozumSuresi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("personelId")
                        .HasColumnType("int");

                    b.Property<int?>("raporlayanEkipmanId")
                        .HasColumnType("int");

                    b.HasKey("raporId");

                    b.HasIndex("personelId");

                    b.HasIndex("raporlayanEkipmanId");

                    b.ToTable("VakaRaporu");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Vardiya", b =>
                {
                    b.Property<int>("vardiyaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vardiyaId"));

                    b.Property<string>("calismaBolgesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ekipSayisi")
                        .HasColumnType("int");

                    b.Property<int?>("ekipmanId")
                        .HasColumnType("int");

                    b.Property<string>("ekipmanOperatoru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ekipmanSayisi")
                        .HasColumnType("int");

                    b.Property<string>("operasyonRiskSeviyesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("operasyonTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("personelSayisi")
                        .HasColumnType("int");

                    b.Property<int>("toplaVardiyaSuresi")
                        .HasColumnType("int");

                    b.Property<string>("vardiyaAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("vardiyaBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("vardiyaBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("vardiyaDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vardiyaIsgSorumlusu")
                        .HasColumnType("int");

                    b.Property<string>("vardiyaNotlari")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("vardiyaOlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("vardiyaSorumlusu")
                        .HasColumnType("int");

                    b.Property<string>("vardiyaSupervizoru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vardiyaTanimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vardiyaTeknikSorumlusu")
                        .HasColumnType("int");

                    b.Property<string>("vardiyaTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vardiyaId");

                    b.HasIndex("ekipmanId");

                    b.HasIndex("vardiyaIsgSorumlusu");

                    b.HasIndex("vardiyaSorumlusu");

                    b.HasIndex("vardiyaTeknikSorumlusu");

                    b.ToTable("Vardiya");

                    b.HasData(
                        new
                        {
                            vardiyaId = 1,
                            calismaBolgesi = "Batı Ocağı",
                            ekipSayisi = 1,
                            ekipmanOperatoru = "Ahmet Operatör",
                            ekipmanSayisi = 2,
                            operasyonRiskSeviyesi = "Orta",
                            operasyonTipi = "Dekapaj",
                            personelSayisi = 5,
                            toplaVardiyaSuresi = 8,
                            vardiyaAdi = "Gündüz Vardiyası A",
                            vardiyaBaslangicTarihi = new DateTime(2026, 5, 9, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            vardiyaBitisTarihi = new DateTime(2026, 5, 9, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            vardiyaDurumu = "Aktif",
                            vardiyaIsgSorumlusu = 1,
                            vardiyaNotlari = "Zemin kaygan, dikkatli olunmalı.",
                            vardiyaOlusturmaTarihi = new DateTime(2026, 5, 9, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            vardiyaSorumlusu = 1,
                            vardiyaSupervizoru = "Büşra Arslan",
                            vardiyaTanimi = "08:00 - 16:00 Kazı Operasyonu",
                            vardiyaTeknikSorumlusu = 1,
                            vardiyaTipi = "Üretim"
                        });
                });

            modelBuilder.Entity("Kirici", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekipman", "Ekipman")
                        .WithOne()
                        .HasForeignKey("Kirici", "ekipmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipman");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.AcilDurumIletisim", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Personel", "Personel")
                        .WithMany("AcilDurumKisileri")
                        .HasForeignKey("personelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Aksiyon", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekip", "Ekip")
                        .WithMany()
                        .HasForeignKey("ekipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Minemation.Domain.Entities.Vaka", "Vaka")
                        .WithMany()
                        .HasForeignKey("vakaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekip");

                    b.Navigation("Vaka");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Ekip", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("personelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Minemation.Domain.Entities.Vardiya", "Vardiya")
                        .WithMany()
                        .HasForeignKey("vardiyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.EkipmanRaporu", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Rapor", "Rapor")
                        .WithOne()
                        .HasForeignKey("Minemation.Domain.Entities.EkipmanRaporu", "raporId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rapor");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Ekskavator", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekipman", "Ekipman")
                        .WithOne()
                        .HasForeignKey("Minemation.Domain.Entities.Ekskavator", "ekipmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipman");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.ElAletleri", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekipman", "Ekipman")
                        .WithOne()
                        .HasForeignKey("Minemation.Domain.Entities.ElAletleri", "ekipmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipman");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Hafriyat", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekipman", "Ekipman")
                        .WithOne()
                        .HasForeignKey("Minemation.Domain.Entities.Hafriyat", "ekipmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipman");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Kepce", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekipman", "Ekipman")
                        .WithOne()
                        .HasForeignKey("Minemation.Domain.Entities.Kepce", "ekipmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipman");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.LogKaydi", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekipman", "Ekipman")
                        .WithMany()
                        .HasForeignKey("ekipmanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Minemation.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("personelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ekipman");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.PersonelRaporu", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Rapor", "Rapor")
                        .WithOne()
                        .HasForeignKey("Minemation.Domain.Entities.PersonelRaporu", "raporId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rapor");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Rapor", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekipman", "Ekipman")
                        .WithMany()
                        .HasForeignKey("ekipmanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Minemation.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("personelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ekipman");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.SaglikBilgileri", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Personel", "Personel")
                        .WithOne("SaglikBilgileri")
                        .HasForeignKey("Minemation.Domain.Entities.SaglikBilgileri", "personelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekipman", "Ekipman")
                        .WithOne("Sensor")
                        .HasForeignKey("Minemation.Domain.Entities.Sensor", "ekipmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipman");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.SensorVerisi", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("ekipmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Minemation.Domain.Entities.Vardiya", "Vardiya")
                        .WithMany()
                        .HasForeignKey("vardiyaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sensor");

                    b.Navigation("Vardiya");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.TakipCihazi", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekipman", "Ekipman")
                        .WithMany()
                        .HasForeignKey("ekipmanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Minemation.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("personelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ekipman");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Vaka", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekipman", "IlgiliEkipman")
                        .WithMany()
                        .HasForeignKey("ilgiliEkipmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Minemation.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("personelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Minemation.Domain.Entities.Ekipman", "RaporlayanEkipman")
                        .WithMany()
                        .HasForeignKey("raporlayanEkipmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IlgiliEkipman");

                    b.Navigation("Personel");

                    b.Navigation("RaporlayanEkipman");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.VakaRaporu", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("personelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Minemation.Domain.Entities.Rapor", "Rapor")
                        .WithOne()
                        .HasForeignKey("Minemation.Domain.Entities.VakaRaporu", "raporId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Minemation.Domain.Entities.Ekipman", "RaporlayanEkipman")
                        .WithMany()
                        .HasForeignKey("raporlayanEkipmanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Personel");

                    b.Navigation("Rapor");

                    b.Navigation("RaporlayanEkipman");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Vardiya", b =>
                {
                    b.HasOne("Minemation.Domain.Entities.Ekipman", "Ekipman")
                        .WithMany()
                        .HasForeignKey("ekipmanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Minemation.Domain.Entities.Personel", "IsgSorumlusuPersonel")
                        .WithMany()
                        .HasForeignKey("vardiyaIsgSorumlusu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Minemation.Domain.Entities.Personel", "VardiyaSorumlusuPersonel")
                        .WithMany()
                        .HasForeignKey("vardiyaSorumlusu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Minemation.Domain.Entities.Personel", "TeknikSorumlusuPersonel")
                        .WithMany()
                        .HasForeignKey("vardiyaTeknikSorumlusu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ekipman");

                    b.Navigation("IsgSorumlusuPersonel");

                    b.Navigation("TeknikSorumlusuPersonel");

                    b.Navigation("VardiyaSorumlusuPersonel");
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Ekipman", b =>
                {
                    b.Navigation("Sensor")
                        .IsRequired();
                });

            modelBuilder.Entity("Minemation.Domain.Entities.Personel", b =>
                {
                    b.Navigation("AcilDurumKisileri");

                    b.Navigation("SaglikBilgileri")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
